### ISSUE TITLE
Provide pdf

### ISSUE THREAD

**Issue by joernweissenborn** [s-weigand/master-thesis-template#1]
So as an interested reader, i would just like to have a link to like an ci artifact instead of installing a few gb of Tex stuff just to have a quick look

**Comment by s-weigand** [comment]
CI artifacts are uploaded each build (see [here](https://github.com/s-weigand/master-thesis-template/actions/runs/3995029467)), but they [expire after 1-90days](https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization)
